### PR TITLE
add test coverage workflow

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Comment by danieleades** [comment]
hmm. will need to figure out why the tests fail when run by cargo-tarpaulin. any ideas @foresterre?

**Comment by danieleades** [comment]
configured tarpaulin to use a single thread. should have read the README...

**Comment by foresterre** [comment]
Thank you for your PR. I would like to add code coverage, but am not sure whether I would like to also maintain and manage codecov (i.e. an external service outside of Github and crates.io).

To that end:

* What are the options for running code coverage without a service like codecov? 
* What would be the impact of adding codecov to the project?
* Would I need to sign up for an account with codecov (or perhaps I already have an account, but would need to configure certain options)? Who would manage codecov for this project? Are there (potentially future) payments involved for having codecov generate reports based on the coverage data generated by cargo-tarpoulin?

**Review by foresterre — COMMENTED** [review]
Thank you for your PR. I would like to add code coverage, but am not sure whether I would like to also maintain and manage codecov (i.e. an external service outside of Github and crates.io).

To that end:

* What are the options for running code coverage without a service like codecov? 
* What would be the impact of adding codecov to the project?
* Would I need to sign up for an account with codecov (or perhaps I already have an account, but would need to configure certain options)? Who would manage codecov for this project? Are there (potentially future) payments involved for having codecov generate reports based on the coverage data generated by cargo-tarpoulin?

**Comment by danieleades** [comment]
- codecov is free for public repos, though I think will need  a one time registration (using your GitHub account)
- there's no additional setup or maintenance required, including for any new repos you might create from the same account. It will Just Work.
- all codecov is doing here is posting a comment with a pretty report. It's able to do that by also tracking the coverage of the base commit of the PR. Tarpaulin is doing the heavy lifting, really
- you *could* use tarpaulin alone, and set a coverage threshold on the command line. I'm not sure I'd recommend this though. I usually prefer to treat the coverage as informational, than as a strict quality gate
- you can always remove it again if you don't love it

**Comment by foresterre** [comment]
Could you please squash these commits; I'll give it a shot and see whether I like it :)

**Review by foresterre — CHANGES_REQUESTED** [review]
Can you please squash or rebase these commits into one commit?

**Review by foresterre — APPROVED** [review]

**Comment by foresterre** [comment]
Thanks!

**Pull request merged**
